# Generated by Django 4.2.5 on 2023-10-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='iban',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
