# Generated by Django 4.2.5 on 2023-11-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_alter_account_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='iban',
        ),
    ]
